title: ESPHome 
icon: mdi:chip
cards:

  - type: entities
    title: 'Input energy monitor'
    show_header_toggle: false
    state_color: true
    entities:
      - binary_sensor.energy_monitor_input_online
      - sensor.energy_monitor_input_ssid
      - sensor.ip_energy_monitor_input
      - sensor.status_energy_monitor_input
      - type: divider
      - sensor.input_voltage
      - sensor.input_current
      - sensor.input_power
      - sensor.input_power_factor
      - sensor.input_frequency

      - entity: sensor.pzem_energy_daily_day
        type: custom:multiple-entity-row
        name: Сутки
        show_state: false
        entities:
          - entity: sensor.pzem_energy_daily_day
            name: день
          - entity: sensor.pzem_energy_daily_night
            name: ночь

      - entity: sensor.pzem_energy_monthly_day
        type: custom:multiple-entity-row
        name: Месяц
        show_state: false
        entities:
          - entity: sensor.pzem_energy_monthly_day
            name: день
          - entity: sensor.pzem_energy_monthly_night
            name: ночь

      - button.restart_energy_monitor_input

  - type: entities
    title: 'Gas-heater control'
    show_header_toggle: false
    state_color: true
    entities:
      - binary_sensor.gas_heater_control_online
      - sensor.gas_heater_control_ssid
      - sensor.ip_gas_heater_control
      - sensor.status_gas_heater_control
      - type: divider
      - sensor.water_system_temperature
      - sensor.water_out_temperature
      - switch.gas_heater_relay
      - button.restart_gas_heater_control
      
#   - type: entities
#     title: 'Wall switch'
#     show_header_toggle: false
#     state_color: true
#     entities:
#       - binary_sensor.wall_switch_bedroom
#       - sensor.ip_wall_switch_bedroom
#       - sensor.status_wall_switch_bedroom
#       - type: divider
#       - binary_sensor.button_wall_switch_bedroom
#       - switch.relay_wall_switch_bedroom
#       - switch.restart_wall_switch_bedroom

  - type: entities
    title: 'Coridor light'
    show_header_toggle: false
    state_color: true
    entities:
      - binary_sensor.coridor_light_online
      - sensor.coridor_light_ssid
      - sensor.ip_coridor_light
      - sensor.status_coridor_light
      - type: divider
      - binary_sensor.coridor_night_light_button
      - switch.coridor_night_light_relay
      - button.restart_coridor_light
      
  - type: entities
    title: 'BME280'
    show_header_toggle: false
    state_color: true
    entities:
      - binary_sensor.outside_sensor_online
      - sensor.ip_outside_sensor
      - sensor.status_outside_sensor
      - type: divider
      - sensor.outside_temperature
    #   - sensor.bme280_humidity
    #   - sensor.bme280_pressure
    #   - sensor.bme280_pressure_in_mmhg
    #   - sensor.dew_point
      - button.restart_outside_sensor

#   - type: entities
#     title: 'Бойлер'
#     show_header_toggle: false
#     state_color: true
#     entities:
#       - binary_sensor.bw_shp8_status
#       - sensor.bw_shp8_ip_address
#       - sensor.bw_shp8_wifi_signal_sensor
#       - type: divider
#       - sensor.bw_shp8_current
#       - sensor.bw_shp8_power
#       - sensor.bw_shp8_voltage
#       - switch.bw_shp8_relay
#       - switch.bw_shp8_restart_switch

  - type: conditional
    conditions:
      - entity: binary_sensor.magic_light_online
        state: "on"
    card:
      type: entities
      title: 'Magic light'
      state_color: true
#   - type: entities
#     title: 'Magic Light'
#     show_header_toggle: false
#     state_color: true
      entities:
      - binary_sensor.magic_light_online
      - sensor.ip_magic_light
      - sensor.status_magic_light
      - type: divider
      - light.magic_light
      - button.restart_magic_light

  - type: conditional
    conditions:
      - entity: binary_sensor.weather_display_online
        state: "on"
    card:
      type: entities
      title: 'Wether display'
      state_color: true
      entities:
        - binary_sensor.weather_display_online
        - sensor.ip_weather_display
        - sensor.status_weather_display
        - type: divider
        - sensor.bme280_humidity
        - sensor.bme280_pressure
        - sensor.bme280_pressure_in_mmhg
        - sensor.bme280_temperature
        - type: divider
        - sensor.weather_display_esphome_version
        - sensor.uptime_weather_display
        - button.restart_weather_display
        - input_select.oled_page

  - type: conditional
    conditions:
      - entity: binary_sensor.sonoff_mini_001_online
        state: "on"
    card:
      type: entities
      title: 'Bathroom vent'
      state_color: true
      entities:
        - binary_sensor.sonoff_mini_001_online
        - sensor.sonoff_mini_001_ssid
        - sensor.ip_sonoff_mini_001
        - sensor.status_sonoff_mini_001
        - type: divider
        - binary_sensor.sonoff_mini_001_relay
        - binary_sensor.sonoff_mini_001_status
        - switch.sonoff_mini_001_switch
        - button.restart_sonoff_mini_001


      
  - type: entities
    title: 'Zigbee розетки'
    show_header_toggle: false
    state_color: true
    entities:
      - switch.my_pc_switch
      - switch.dishwasher
      - switch.humidifier
      - switch.basement_vent

  - type: entities
    title: 'Wi-Fi розетки'
    show_header_toggle: false
    state_color: true
    entities:
      - switch.xiaomi_power_strip
      - switch.undertabble_mi_wifi_socket
      - type: divider
      - switch.broadlink_1
      - switch.broadlink_2
      - switch.broadlink_3
