- alias: Свет в детской - потолочный
  trigger:
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "single_left"
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_c_bedroom_left
      
- alias: Свет в детской - подкроватный на 10%
  trigger:
    - platform: state
      entity_id: switch.wall_switch_c_bedroom_right
      to: 'on'
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "single_right"
  action:
    - service: light.turn_on
      data:
        entity_id: light.magic_light
        brightness_pct: 10
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.wall_switch_c_bedroom_right
              state: "off"
          sequence:
            - service: switch.turn_on
              entity_id: switch.wall_switch_c_bedroom_right
        - conditions:
            - condition: state
              entity_id: switch.wall_switch_c_bedroom_center
              state: "on"
          sequence:
            - service: switch.turn_off
              entity_id: switch.wall_switch_c_bedroom_center

- alias: Свет в детской - подкроватный на 100%
  trigger:
    - platform: state
      entity_id: switch.wall_switch_c_bedroom_center
      to: 'on'
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "double_right"
  action:
    - service: light.turn_on
      data:
        entity_id: light.magic_light
        brightness_pct: 100
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.wall_switch_c_bedroom_center
              state: "off"
          sequence:
            - service: switch.turn_on
              entity_id: switch.wall_switch_c_bedroom_center
        - conditions:
            - condition: state
              entity_id: switch.wall_switch_c_bedroom_right
              state: "on"
          sequence:
            - service: switch.turn_off
              entity_id: switch.wall_switch_c_bedroom_right


- alias: Свет в детской - подкроватный выключить
  trigger:
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "hold_right"
    - platform: state
      entity_id: switch.wall_switch_c_bedroom_right
      to: 'off'
    - platform: state
      entity_id: switch.wall_switch_c_bedroom_center
      to: 'off'

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.from_state.state == 'on' }}"
            - condition: state
              entity_id:
                - switch.wall_switch_c_bedroom_right
                - switch.wall_switch_c_bedroom_center
              state: "off"
            # - condition: state
            #   entity_id: switch.wall_switch_c_bedroom_right
            #   state: "off"
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.magic_light

        - conditions: "{{ trigger.to_state.state == 'hold_right' }}"
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.magic_light
            - service: switch.turn_off
              entity_id: 
                - switch.wall_switch_c_bedroom_right
                - switch.wall_switch_c_bedroom_center

- alias: Свет в детской - выключить
  trigger:
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "single_both"
  action:
    - service: switch.turn_off
      entity_id:
        - switch.wall_switch_c_bedroom_left
        - switch.wall_switch_c_bedroom_center
        - switch.wall_switch_c_bedroom_right

    - service: light.turn_off
      data:
        entity_id: light.magic_light
