############################################################################################################
##### 30 сек расчет
- alias: 00_power_counter
  initial_state: true
  trigger:
    - platform: time_pattern
      seconds: '/30'
  action:
##### Общее потребление
    - service: mqtt.publish
      data_template:
        topic: "power/input_energy/today"
        payload: '{{(states.sensor.mqtt_power_today_input_energy.state | float +
                    (states.sensor.load_input_energy.state | float /120000))|round(5)}}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/input_energy/month"
        payload: '{{(states.sensor.mqtt_power_month_input_energy.state | float +
                    (states.sensor.load_input_energy.state | float /120000))|round(5)}}'
        retain: true  
##### Общее потребление по датчикам
    - service: mqtt.publish
      data_template:
        topic: "power/total_energy/today"
        payload: '{{(states.sensor.mqtt_power_today_total_energy.state | float +
                    (states.sensor.load_total_energy.state | float /120000))|round(5)}}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/total_energy/month"
        payload: '{{(states.sensor.mqtt_power_month_total_energy.state | float +
                    (states.sensor.load_total_energy.state | float /120000))|round(5)}}'
        retain: true  

##### Wi-Fi 3+3
    - service: mqtt.publish
      data_template:
        topic: "power/xiaomi_power_strip/today"
        payload: '{{(states.sensor.mqtt_power_today_xiaomi_power_strip.state | float +
                    (states.sensor.load_xiaomi_power_strip.state | float /120000))|round(5)}}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/xiaomi_power_strip/month"
        payload: '{{(states.sensor.mqtt_power_month_xiaomi_power_strip.state | float +
                    (states.sensor.load_xiaomi_power_strip.state | float /120000))|round(5)}}'
        retain: true

##### Broadlink 1
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_1/today"
        payload: '{{(states.sensor.mqtt_power_today_broadlink_1.state | float +
                    (states.sensor.load_broadlink_1.state | float /120000))|round(5)}}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_1/month"
        payload: '{{(states.sensor.mqtt_power_month_broadlink_1.state | float +
                    (states.sensor.load_broadlink_1.state | float /120000))|round(5)}}'
        retain: true

##### Broadlink 2
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_2/today"
        payload: '{{(states.sensor.mqtt_power_today_broadlink_2.state | float +
                    (states.sensor.load_broadlink_2.state | float /120000))|round(5)}}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_2/month"
        payload: '{{(states.sensor.mqtt_power_month_broadlink_2.state | float +
                    (states.sensor.load_broadlink_2.state | float /120000))|round(5)}}'
        retain: true

#BlitzWolf BW-SHP8
    - service: mqtt.publish
      data_template:
        topic: "power/bw_shp8/today"
        payload: '{{(states.sensor.mqtt_power_today_bw_shp8.state | float +
                    (states.sensor.load_bw_shp8.state | float /120000))|round(5)}}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/bw_shp8/month"
        payload: '{{(states.sensor.mqtt_power_month_bw_shp8.state | float +
                    (states.sensor.load_bw_shp8.state | float /120000))|round(5)}}'
        retain: true

#BlitzWolf BW-SHP13_1
    - service: mqtt.publish
      data_template:
        topic: "power/dishwasher/today"
        payload: '{{(states.sensor.mqtt_power_today_dishwasher.state | float +
                    (states.sensor.load_dishwasher.state | float /120000))|round(5)}}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/dishwasher/month"
        payload: '{{(states.sensor.mqtt_power_month_dishwasher.state | float +
                    (states.sensor.load_dishwasher.state | float /120000))|round(5)}}'
        retain: true

#BlitzWolf BW-SHP13_2
    - service: mqtt.publish
      data_template:
        topic: "power/humidifier/today"
        payload: '{{(states.sensor.mqtt_power_today_humidifier.state | float +
                    (states.sensor.load_humidifier.state | float /120000))|round(5)}}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/humidifier/month"
        payload: '{{(states.sensor.mqtt_power_month_humidifier.state | float +
                    (states.sensor.load_humidifier.state | float /120000))|round(5)}}'
        retain: true

############################################################################################################
##### Начало дня    
- alias: 00_power_new_day
  initial_state: true
  trigger:
    - platform: time
      at: '00:00:05'
  action:
##### Запись данных за прошедший день
##### Общее потребление
    - service: mqtt.publish
      data_template:
        topic: "power/input_energy/yesterday"
        payload: '{{(states.sensor.mqtt_power_today_input_energy.state | float )|round(5)}}'
        retain: true 
##### Общее потребление по датчикам
    - service: mqtt.publish
      data_template:
        topic: "power/total_energy/yesterday"
        payload: '{{(states.sensor.mqtt_power_today_total_energy.state | float )|round(5)}}'
        retain: true 
##### Удлинитель 3+3        
    - service: mqtt.publish
      data_template:
        topic: "power/xiaomi_power_strip/yesterday"
        payload: '{{(states.sensor.mqtt_power_today_xiaomi_power_strip.state | float )|round(5)}}'
        retain: true
##### Broadlink 1
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_1/yesterday"
        payload: '{{(states.sensor.mqtt_power_today_broadlink_1.state | float )|round(5)}}'
        retain: true
##### Broadlink 2
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_2/yesterday"
        payload: '{{(states.sensor.mqtt_power_today_broadlink_2.state | float )|round(5)}}'
        retain: true
#BlitzWolf BW-SHP8      
    - service: mqtt.publish
      data_template:
        topic: "power/bw_shp8/yesterday"
        payload: '{{(states.sensor.mqtt_power_today_bw_shp8.state | float )|round(5)}}'
        retain: true
#BlitzWolf BW-SHP13_1      
    - service: mqtt.publish
      data_template:
        topic: "power/dishwasher/yesterday"
        payload: '{{(states.sensor.mqtt_power_today_dishwasher.state | float )|round(5)}}'
        retain: true
#BlitzWolf BW-SHP13_2    
    - service: mqtt.publish
      data_template:
        topic: "power/humidifier/yesterday"
        payload: '{{(states.sensor.mqtt_power_today_humidifier.state | float )|round(5)}}'
        retain: true

    - delay: 00:00:05

##### Обнуление данных текущего дня
##### Общее потребление
    - service: mqtt.publish
      data_template:
        topic: "power/input_energy/today"
        payload: '{{ 0.0 }}'
        retain: true
##### Общее потребление по датчикам
    - service: mqtt.publish
      data_template:
        topic: "power/total_energy/today"
        payload: '{{ 0.0 }}'
        retain: true
##### Удлинитель 3+3 
    - service: mqtt.publish
      data_template:
        topic: "power/xiaomi_power_strip/today"
        payload: '{{ 0.0 }}'
        retain: true
##### Broadlink 1 
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_1/today"
        payload: '{{ 0.0 }}'
        retain: true
##### Broadlink 2
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_2/today"
        payload: '{{ 0.0 }}'
        retain: true
#BlitzWolf BW-SHP8
    - service: mqtt.publish
      data_template:
        topic: "power/bw_shp8/today"
        payload: '{{ 0.0 }}'
        retain: true
#BlitzWolf BW-SHP13_1
    - service: mqtt.publish
      data_template:
        topic: "power/dishwasher/today"
        payload: '{{ 0.0 }}'
        retain: true
#BlitzWolf BW-SHP13_2
    - service: mqtt.publish
      data_template:
        topic: "power/humidifier/today"
        payload: '{{ 0.0 }}'
        retain: true

############################################################################################################
##### Начало месяца
- alias: 00_power_new_month
  initial_state: true
  trigger:
    - platform: time
      at: '00:00:10'
  condition:
    - condition: template
      value_template: '{{ now().day == 1 }}'
  action:
 
##### Запись данных за прошедший месяц
##### Общее потребление
    - service: mqtt.publish
      data_template:
        topic: "power/input_energy/lastmonth"
        payload: '{{(states.sensor.mqtt_power_month_input_energy.state | float )|round(5)}}'
        retain: true 
##### Общее потребление по датчикам
    - service: mqtt.publish
      data_template:
        topic: "power/total_energy/lastmonth"
        payload: '{{(states.sensor.mqtt_power_month_total_energy.state | float )|round(5)}}'
        retain: true 
##### Broadlink 1
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_1/lastmonth"
        payload: '{{(states.sensor.mqtt_power_month_broadlink_1.state | float )|round(5)}}'
        retain: true
##### Broadlink 2
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_2/lastmonth"
        payload: '{{(states.sensor.mqtt_power_month_broadlink_2.state | float )|round(5)}}'
        retain: true
#BlitzWolf BW-SHP8
    - service: mqtt.publish
      data_template:
        topic: "power/bw_shp8/lastmonth"
        payload: '{{(states.sensor.mqtt_power_month_bw_shp8.state | float )|round(5)}}'
        retain: true
#BlitzWolf BW-SHP13_1
    - service: mqtt.publish
      data_template:
        topic: "power/dishwasher/lastmonth"
        payload: '{{(states.sensor.mqtt_power_month_dishwasher.state | float )|round(5)}}'
        retain: true
#BlitzWolf BW-SHP13_2
    - service: mqtt.publish
      data_template:
        topic: "power/humidifier/lastmonth"
        payload: '{{(states.sensor.mqtt_power_month_humidifier.state | float )|round(5)}}'
        retain: true

    - delay: 00:00:05

##### Обнуление данных текущего месяца
##### Общее потребление
    - service: mqtt.publish
      data_template:
        topic: "power/input_energy/month"
        payload: '{{ 0.0 }}'
        retain: true
##### Общее потребление по датчикам
    - service: mqtt.publish
      data_template:
        topic: "power/total_energy/month"
        payload: '{{ 0.0 }}'
        retain: true
##### Удлинитель 3+3 
    - service: mqtt.publish
      data_template:
        topic: "power/xiaomi_power_strip/month"
        payload: '{{ 0.0 }}'
        retain: true
##### Broadlink 1
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_1/month"
        payload: '{{ 0.0 }}'
        retain: true
##### Broadlink 2
    - service: mqtt.publish
      data_template:
        topic: "power/broadlink_2/month"
        payload: '{{ 0.0 }}'
        retain: true
#BlitzWolf BW-SHP8
    - service: mqtt.publish
      data_template:
        topic: "power/bw_shp8/month"
        payload: '{{ 0.0 }}'
        retain: true
#BlitzWolf BW-SHP13_1
    - service: mqtt.publish
      data_template:
        topic: "power/dishwasher/month"
        payload: '{{ 0.0 }}'
        retain: true
#BlitzWolf BW-SHP13_2
    - service: mqtt.publish
      data_template:
        topic: "power/humidifier/month"
        payload: '{{ 0.0 }}'
        retain: true