- alias: Ночник в коридоре - включить с заходом солнца
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.coridor_night_light_relay
  mode: single
  
- alias: Ночник в коридоре - выключить в полночь
  description: ''
  trigger:
  - platform: time
    at: 00:00
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.coridor_night_light_relay
  mode: single
    
- alias: Ночник в коридоре - восстановить после включения
  description: 'Включает свет в коридоре после отключения электричества(по подключению светильника)'
  trigger:
  - platform: state
    entity_id: binary_sensor.coridor_light
    to: "on"
    for:
      seconds: 5
  condition:
  - condition: sun
    after: sunset
  - condition: time
    before: 00:00
  action:
  - service: switch.turn_on
    entity_id: switch.coridor_night_light_relay
  mode: single
