- alias: 'Telegram bot that reply pong to ping'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - service: notify.telegram
      data:
        message: 'pong'
        
- alias: 'washing machine end washing'
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine
    from: "on"
    to: "off"
  condition:
    - condition: state
      entity_id: switch.broadlink_1
      state: "on"
  action:
    - service: notify.telegram
      data:
        message: 'Машинка достирала'
    - service: notify.telegram_olga
      data:
        message: 'Машинка достирала'

- alias: 'washing power issue'
  trigger:
    platform: state
    entity_id: switch.broadlink_1
    from: "on"
    to: "off"
  condition:
    - condition: state
      entity_id: binary_sensor.washing_machine # switch.broadlink_1
      state: "on"
  action:
    - service: notify.telegram
      data:
        message: 'Розетка стиралки отключилась. Включить?'
        data:
          inline_keyboard:
            - 'Да:/washing_machine_turn_on, Нет:/washing_machine_turn_off'

    - service: notify.telegram_olga
      data:
        message: 'Розетка стиралки отключилась. Включить?'
        data:
          inline_keyboard:
            - 'Да:/washing_machine_turn_on, Нет:/washing_machine_turn_off'

- alias: 'washing power restore'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: '/washing_machine_turn_on'
  action:
    - service: notify.telegram
      data:
        message: 'Розетку уже кто-то включил'
    - service: switch.turn_on
      entity_id: switch.broadlink_1

- alias: 'Telegram Weather'
  trigger:
    platform: time
    at: 07:30:00
  action:
    - service: notify.telegram
      data:
        message: |
          {%- set state = states('weather.home_assistant') -%}
          {% if state == 'clear-night' %} Ясно, ночь {{"\U0001F315"}}
          {% elif state == 'cloudy' %} Облачно {{"\U00002601"}}
          {% elif state == 'exceptional' %} Предупреждение {{"\U0001F6A8"}}
          {% elif state == 'fog' %} Туман {{"\U0001F32B"}}
          {% elif state == 'hail' %} Град {{"\U0001F328"}}{{"\U0001F328"}}
          {% elif state == 'lightning' %} Молния {{"\U0001F329"}}
          {% elif state == 'lightning-rainy' %} Гроза {{"\U000026C8"}}
          {% elif state == 'partlycloudy' %} Переменная облачность {{"\U000026C5"}}
          {% elif state == 'pouring' %} Ливень {{"\U0001F327"}}{{"\U0001F327"}}
          {% elif state == 'rainy' %} Дождь {{"\U0001F327"}}
          {% elif state == 'snowy' %} Снег {{"\U0001F328"}}
          {% elif state == 'snowy-rainy' %} Снег с дождем {{"\U0001F328"}}{{"\U0001F327"}}
          {% elif state == 'sunny' %} Ясно {{"\U00002600"}}
          {% elif state == 'windy' %} Ветрено {{"\U0001F32C"}}
          {% elif state == 'windy-variant' %} Ветрено {{"\U0001F32C"}}
          {% else %} Нет данных {% endif %}
          Температура {{ state_attr('weather.home_assistant', 'temperature') }} °C
          Ветер {{ state_attr('weather.home_assistant', 'wind_speed') }} км/ч

- alias: 'Gas heater notify'
  trigger:
    platform: state
    entity_id: switch.gas_heater_relay
  action:
    - service: notify.telegram
      data:
        message: "Автоматика отработала. Газовый котел {{ trigger.to_state.state }}"






