- id: '1578759248643'
  alias: Мой ПК - включить, когда я дома
  description: ''
  trigger:
  - entity_id: person.sergei
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: switch.my_pc
    state: 'off'
  action:
#   - service: script.wakeup_my_pc
  - service: switch.turn_on
    entity_id: switch.my_pc
  - service: notify.mobile_app_mi_9
    data:
      title: "WOL"
      message: "Magic pockets sent"

- alias: Мой ПК - включить пилот
  trigger:
  - entity_id: switch.my_pc
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.undertabble_mi_wifi_socket
#   - service: switch.turn_on
#     entity_id: switch.tv
#   - delay: 
#       seconds: 2
#   - service: switch.turn_on
#     entity_id: switch.audio1

- alias: Мой ПК - выключить пилот
  trigger:
  - entity_id: switch.my_pc
    from: 'on'
    platform: state
    to: 'off'
    for:
      seconds: 30
  action:
#   - service: switch.turn_on
#     entity_id: switch.audio1
#   - delay:
#       seconds: 3
#   - service: switch.turn_on
#     entity_id: switch.tv
  - service: switch.turn_off
    entity_id: switch.undertabble_mi_wifi_socket
      
- alias: Мой ПК - выключение по таймеру
  initial_state: true
  trigger:
# Таймер
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.pc
  condition:
  - condition: state
    entity_id: switch.my_pc
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.my_pc