- id: 'Мой ПК - включить, когда я дома'
  alias: Мой ПК - включить, когда я дома
  description: ''
  trigger:
  - entity_id: person.sergei
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: switch.my_pc
    state: 'off'
  action:
#   - service: script.wakeup_my_pc
  - service: switch.turn_on
    entity_id: switch.my_pc
  - service: notify.mobile_app_mi_9
    data:
      title: "WOL"
      message: "Magic pockets sent"

- alias: Мой ПК - пилот
  id: "Мой ПК - пилот"
  trigger:
  - platform: state
    entity_id: switch.my_pc
  action:
    - choose:
        - conditions: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: switch.turn_on
              data:
                entity_id: switch.undertabble_mi_wifi_socket
        - conditions: "{{ trigger.to_state.state == 'off' }}"
          sequence:
            - service: switch.turn_off
              data:
                entity_id: switch.undertabble_mi_wifi_socket

- alias: Мой ПК - выключение по таймеру
  id: "Мой ПК - выключение по таймеру"
  initial_state: true
  trigger:
# Таймер
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.pc
  condition:
  - condition: state
    entity_id: switch.my_pc
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.my_pc