# Включение света в ванной по датчику движения
- alias: Свет в ванной - включение по датчику движения
  id: "Свет в ванной - включение по датчику движения"
  initial_state: false
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_occupancy
      to: 'on'
  condition:
    - condition: state
      entity_id: light.bath
      state: 'off'
    - condition: time
      after: 00:00:00
    - condition: sun
      before: sunrise
  action:
    - service: light.turn_on
      entity_id: light.bath

# Включение таймера освещения в ванной
- alias: Свет в ванной - включение таймера освещения в ванной
  id: "Свет в ванной - включение таймера освещения в ванной"
  initial_state: false
  trigger:
    - platform: state
      entity_id: light.bath
      to: 'on'
  condition:
    - condition: time
      after: 00:00:00
    - condition: sun
      before: sunrise
  action:
    - service: timer.cancel
      entity_id: timer.bath_light
    - service: timer.start
      entity_id: timer.bath_light

# Автоматическое выключение света в ванной по таймеру
- alias: Свет в ванной - автоматическое выключение света по таймеру
  id: "Свет в ванной - автоматическое выключение света по таймеру"
  initial_state: false
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bath_light
  condition:
    - condition: state
      entity_id: light.bath
      state: 'on'
    - condition: time
      after: 00:00:00
    - condition: sun
      before: sunrise
  action:
    - service: light.turn_off
      entity_id: light.bath
      
# Сброс таймера если свет в ванной выключен
- alias: Свет в ванной - сброс таймера если свет в ванной выключен
  id: "Свет в ванной - сброс таймера если свет в ванной выключен"
  initial_state: false
  trigger:
    - platform: state
      entity_id: light.bath
      from: 'on'
      to: 'off'
  condition:
    - condition: time
      after: 00:00:00
    - condition: sun
      before: sunrise
  action:
    - service: timer.cancel
      entity_id: timer.bath_light
    - service: automation.turn_off
      entity_id: automation.svet_v_vannoi_vkliuchenie_po_datchiku_dvizheniia
    - delay: 00:02:00
    - service: automation.turn_on
      entity_id: automation.svet_v_vannoi_vkliuchenie_po_datchiku_dvizheniia

# # Обновление таймера освещения в ванной      
# - alias: Обновление таймера освещения в ванной
#   id: "Обновление таймера освещения в ванной"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x00124b002135564f_occupancy
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: light.bath
#       state: 'on'
#     - condition: time
#       after: 00:00:00
#     - condition: sun
#       before: sunrise
#   action:
#     - service: timer.cancel
#       entity_id: timer.bath_light
#     - service: timer.start
#       entity_id: timer.bath_light

- id: "Датчик движения - коридор - включить подсветку"
  alias: Датчик движения - коридор - включить подсветку
  trigger:
    - platform: state
      to: "on"
      entity_id: binary_sensor.motion_sensor_occupancy
  condition:
    # - condition: time
    #   after: 00:00:00
    - condition: sun
      before: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_led
        brightness_pct: 1
    - service: light.turn_on
      data:
        entity_id: light.coridor_rgb
        color_name: yellow
        brightness_pct: 2
        
- id: "Датчик движения - коридор - выключить подсветку"
  alias: Датчик движения - коридор - выключить подсветку
  trigger:
    - platform: state
      to: "off"
      entity_id: binary_sensor.motion_sensor_occupancy
  condition:
    - condition: state
      entity_id: light.gateway_led
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_led
    - service: light.turn_off
      data:
        entity_id: light.coridor_rgb

- alias: Датчик движения - прихожая - выключить свет
  id: "Датчик движения - прихожая - выключить свет"
  trigger:
    - platform: state
      to: "off"
      entity_id: binary_sensor.bath_motion_sensor_occupancy
  condition:
    - condition: state
      entity_id: light.entrance
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.entrance




