- alias: Круглая кнопка - автоматизации
  id: "kruglaia_knopka_avtomatizatsii"
  mode: parallel
  trigger:
    - platform: state
      entity_id: sensor.mi_round_button_action

  action:
    - choose:

        - conditions: "{{ trigger.to_state.state == 'single' }}"
          sequence:
            - service: homeassistant.turn_on
              data:
                entity_id: automation.svet_v_detskoi_potolochnyi # group.motion_light

        - conditions: "{{ trigger.to_state.state == 'double' }}"
          sequence:
            - service: homeassistant.turn_off
              data:
                entity_id: automation.svet_v_detskoi_potolochnyi # group.motion_light
            # - service: timer.cancel
            #   entity_id: timer.bath_light

        - conditions: "{{ trigger.to_state.state == 'hold' }}"
          sequence:
            - service: switch.toggle
              data:
                entity_id: switch.my_pc

- alias: Круглая кнопка - тест
  id: "Круглая кнопка - тест"
  mode: parallel
  trigger:
    - platform: state
      entity_id: sensor.mi_round_button_action
      to: single
  action:
    - service: light.toggle
      entity_id: light.lr_night_light



