- alias: Круглая кнопка - автоматизации
  id: "kruglaia_knopka_avtomatizatsii"
  trigger:
    - platform: state
      entity_id: sensor.mi_round_button_action

  action:
    - choose:

        - conditions: "{{ trigger.to_state.state == 'single' }}"
          sequence:
            - service: homeassistant.turn_on
              data:
                entity_id: group.motion_light

        - conditions: "{{ trigger.to_state.state == 'double' }}"
          sequence:
            - service: homeassistant.turn_off
              data:
                entity_id: group.motion_light
            - service: timer.cancel
              entity_id: timer.bath_light

        - conditions: "{{ trigger.to_state.state == 'hold' }}"
          sequence:
            - service: switch.toggle
              data:
                entity_id: switch.my_pc





