- alias: Водяной насос - включение
  id: "Водяной насос - включение"
  mode: restart
  trigger:
  - platform: state
    entity_id: switch.gas_heater_relay
    to: 'off'
  - platform: state
    entity_id: sensor.water_system_temperature
    
  condition:
  - condition: state
    entity_id: switch.gas_heater_relay
    state: 'off'
  - condition: state
    entity_id: switch.water_pump
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.water_system_temperature
    above: 30

  action:
  - service: switch.turn_on # 
    entity_id: switch.water_pump
    
- alias: Водяной насос - выключение
  id: "Водяной насос - выключение"
  trigger:
  - platform: numeric_state
    below: 30
    entity_id: sensor.water_system_temperature
  - platform: state
    entity_id: switch.gas_heater_relay
    to: "on"
    
  condition:
#   - condition: state
#     entity_id: switch.gas_heater_relay
#     state: 'off'

  action:
  - service: switch.turn_off # 
    entity_id: switch.water_pump