- alias: Выключатель в прихожей - включить свет в дворике
  id: "Выключатель в прихожей - включить свет в дворике"
  trigger:
    - platform: state
      entity_id:
        - switch.wall_switch_entrance_right
        - switch.patio_switch
      to: "on"
      for: 00:00:02
  action:
    - service: switch.turn_on
      entity_id:
        - switch.patio_switch
        - switch.wall_switch_entrance_right

- alias: Выключатель в прихожей - выключить свет в дворике
  id: "Выключатель в прихожей - выключить свет в дворике"
  trigger:
    - platform: state
      entity_id:
        - switch.wall_switch_entrance_right
        - switch.patio_switch
      to: "off"
      for: 00:00:02
  action:
    - service: switch.turn_off
      entity_id:
        - switch.patio_switch
        - switch.wall_switch_entrance_right

- alias: Выключатель в прихожей - включить свет во дворе
  id: "Выключатель в прихожей - включить свет во дворе"
  trigger:
    - platform: state
      entity_id:
        - switch.wall_switch_entrance_left
        - switch.yard_switch
      to: "on"
      for: 00:00:02
  action:
    - service: switch.turn_on
      entity_id:
        - switch.yard_switch
        - switch.wall_switch_entrance_left

- alias: Выключатель в прихожей - выключить свет во дворе
  id: "Выключатель в прихожей - выключить свет во дворе"
  trigger:
    - platform: state
      entity_id:
        - switch.wall_switch_entrance_left
        - switch.yard_switch
      to: "off"
      for: 00:00:02
  action:
    - service: switch.turn_off
      entity_id:
        - switch.yard_switch
        - switch.wall_switch_entrance_left