- alias: patio light on
  trigger:
    - platform: state
      entity_id:
        - switch.wall_switch_entrance_right
        - switch.patio_switch
      to: "on"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.patio_switch
        - switch.wall_switch_entrance_right

- alias: patio light off
  trigger:
    - platform: state
      entity_id:
        - switch.wall_switch_entrance_right
        - switch.patio_switch
      to: "off"
  action:
    - service: switch.turn_off
      entity_id:
        - switch.patio_switch
        - switch.wall_switch_entrance_right

- alias: yard light on
  trigger:
    - platform: state
      entity_id:
        - switch.wall_switch_entrance_left
        - switch.yard_switch
      to: "on"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.yard_switch
        - switch.wall_switch_entrance_left

- alias: yard light off
  trigger:
    - platform: state
      entity_id:
        - switch.wall_switch_entrance_left
        - switch.yard_switch
      to: "off"
  action:
    - service: switch.turn_off
      entity_id:
        - switch.yard_switch
        - switch.wall_switch_entrance_left