- id: "Очистка уведомлений о паролях"
  alias: Очистка уведомлений о паролях
  initial_state: true
  mode: parallel
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: persistent_notification
        service: create
  condition:
    - condition: template
      value_template: >
        {{ 'supervisor_issue_pwned' in trigger.event.data.service_data.notification_id }}
  action:
    - service: persistent_notification.dismiss
      data:
        notification_id: >
          {{ trigger.event.data.service_data.notification_id }}

- alias: База данных - сжать
  id: "База данных - сжать"
  description: ''
  trigger:
  - platform: time
    at: 03:12
  condition: []
  action:
  - service: recorder.purge
    data:
      keep_days: 3
      repack: true
      apply_filter: true
  mode: single






