- id: motion light on
  alias: motion light on
  trigger:
    - platform: state
      to: "on"
      entity_id: binary_sensor.motion_sensor_occupancy
  condition:
    # - condition: time
    #   after: 00:00:00
    - condition: sun
      before: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_led
        brightness_pct: 1
    - service: light.turn_on
      data:
        entity_id: light.coridor_rgb
        brightness_pct: 2
        
- id: motion light off
  alias: motion light off
  trigger:
    - platform: state
      to: "off"
      entity_id: binary_sensor.motion_sensor_occupancy
  condition:
    - condition: state
      entity_id: light.gateway_led
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_led
    - service: light.turn_off
      data:
        entity_id: light.coridor_rgb

- alias: wall switch coridor center button
  trigger: 
    - platform: state
      entity_id: light.coridor_floor
  action:
    - choose:
        - conditions: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.coridor_rgb
                brightness_pct: 2
        - conditions: "{{ trigger.to_state.state == 'off' }}"
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.coridor_rgb