- id: Датчик движения - коридор - включить подсветку
  alias: motion light on
  trigger:
    - platform: state
      to: "on"
      entity_id: binary_sensor.motion_sensor_occupancy
  condition:
    # - condition: time
    #   after: 00:00:00
    - condition: sun
      before: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_led
        brightness_pct: 1
    - service: light.turn_on
      data:
        entity_id: light.coridor_rgb
        brightness_pct: 2
        
- id: Датчик движения - коридор - выключить подсветку
  alias: motion light off
  trigger:
    - platform: state
      to: "off"
      entity_id: binary_sensor.motion_sensor_occupancy
  condition:
    - condition: state
      entity_id: light.gateway_led
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_led
    - service: light.turn_off
      data:
        entity_id: light.coridor_rgb

- alias: Датчик движения - прихожая - выключить свет
  trigger:
    - platform: state
      to: "off"
      entity_id: binary_sensor.bath_motion_sensor_occupancy
  condition:
    - condition: state
      entity_id: light.entrance
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.entrance

- alias: Выключатель в коридоре - подсветка
  trigger: 
    - platform: state
      entity_id: light.coridor_floor
  action:
    - choose:
        - conditions: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.coridor_rgb
                brightness_pct: 2
        - conditions: "{{ trigger.to_state.state == 'off' }}"
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.coridor_rgb

- alias: Выключатель в гостинной - торшер
  trigger: 
    - platform: state
      entity_id: light.lr_night_light
  action:
    - choose:
        - conditions: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: switch.turn_on
              data:
                entity_id: switch.broadlink_3
        - conditions: "{{ trigger.to_state.state == 'off' }}"
          sequence:
            - service: switch.turn_off
              data:
                entity_id: switch.broadlink_3

- id: Очистка уведомлений о паролях
  alias: Очистка уведомлений о паролях
  initial_state: true
  mode: parallel
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: persistent_notification
        service: create
  condition:
    - condition: template
      value_template: >
        {{ 'supervisor_issue_pwned' in trigger.event.data.service_data.notification_id }}
  action:
    - service: persistent_notification.dismiss
      data:
        notification_id: >
          {{ trigger.event.data.service_data.notification_id }}








