# Configure Home Assistant (frontend, api, etc)
homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  currency: UAH
  customize: !include_dir_merge_named includes/customize
  packages: !include_dir_merge_named includes/packages
  allowlist_external_dirs :
    - /config
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.31.0/24
    - type: homeassistant
  external_url: !secret ext_ip
  internal_url: https://192.168.31.125:8123

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
#   server_port: 433
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem
#   ip_ban_enabled: false
#   login_attempts_threshold: 10

default_config:

recorder: !include includes/recorder.yaml

logger:
    default: warn

wake_on_lan:

#lovelace
lovelace:
  mode: yaml

frontend:
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /hacsfiles/custom-ui/custom-ui.js

# Text to speech
tts:
  - platform: google_translate

# google:
#   client_id: !secret google_client_id 
#   client_secret: !secret google_client_secret

#GAssistant
google_assistant:
  project_id: !secret gassistant_project_id
  api_key: !secret gassistant_api
  exposed_domains:
    - switch
    - light
    - climate
    - media_player
  entity_config:
    sensor.outside_temperature:
      name: Температура на улице
      aliases:
        - out_temp
    sensor.ble_temperature_living_room:
      name: Температура в доме
      aliases:
        - in_temp

# Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key 
    allowed_chat_ids:
      - !secret my_chat
      - !secret olga_chat
      
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret my_chat
    
  - name: telegram_olga
    platform: telegram
    chat_id: !secret olga_chat
# Router
device_tracker:
  - platform: xiaomi
    host: 192.168.31.1
    password: !secret mirouter_pwd
    consider_home: 300
    new_device_defaults:
      track_new_devices: false

# rest_command:
#   narodmon:
#     url: http://narodmon.ru/get?ID={{ID}}&T1={{T1}}&H1={{H1}}&P1={{P1}}

panel_custom:
  - name: config/server_control
    sidebar_title: Server Controls
    sidebar_icon: mdi:server
    module_url: any text
# Example configuration.yaml entry
panel_iframe:
  router:
    title: "Z2M 2"
    url: "/z2m"

sensor: !include_dir_merge_list includes/sensors
binary_sensor: !include_dir_merge_list includes/bin_sensor
automation: !include_dir_merge_list includes/automation
script: !include_dir_merge_named includes/scripts
switch: !include_dir_merge_list includes/switches
template: !include_dir_merge_list includes/templates
mqtt: !include_dir_merge_named includes/mqtt

#Files
light: !include includes/light.yaml
group: !include includes/groups.yaml
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
# input_number: !include includes/input_number.yaml
# input_datetime: !include includes/input_datetime.yaml
input_select: !include includes/input_select.yaml
influxdb: !include includes/influxdb.yaml











