- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /
# deprecated
# - platform: filesize
#   file_paths:
#     - /config/home-assistant_v2.db
      
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  
# - platform: version
#   name: current_ha
#   scan_interval: 1800

- platform: template
  sensors:
    version:
      friendly_name: 'Последняя версия - '
      value_template: '{{ states.update.home_assistant_core_update.attributes["latest_version"] }}'