
- platform: template
  sensors:

    unavailable_now_light:
      friendly_name: "Всего недоступных светильников - "
      value_template: >
        {{ states.light | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | length }}
      attribute_templates:
        entities: >
          {{ states.light | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | map(attribute='entity_id') | list | join('\n') }}
      icon_template: mdi:counter        

    unavailable_now_switch:
      friendly_name: "Всего недоступных реле - "
      value_template: >
        {{ states.switch | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | length }}
      attribute_templates:
        entities: >
          {{ states.switch | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | map(attribute='entity_id') | list | join('\n') }}
      icon_template: mdi:counter 
        
    unavailable_now_sensor:
      friendly_name: "Всего недоступных сенсоров - "
      value_template: >
        {{ states.sensor | selectattr('state', 'equalto', ('unavailable')) | list | length }}
      attribute_templates:
        entities: >
          {{ states.sensor | selectattr('state', 'equalto', ('unavailable')) | map(attribute='entity_id') | list | join('\n') }}
      icon_template: mdi:counter
        
    unavailable_now_binary_sensor:
      friendly_name: "Всего недоступных бинарных сенсоров - "
      value_template: >
        {{ states.binary_sensor | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | length }}
      attribute_templates:
        entities: >
          {{ states.binary_sensor | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | map(attribute='entity_id') | list | join('\n') }}
      icon_template: mdi:counter

# {{expand('group.electricity') | selectattr ('state', 'equalto', 'on') | list | length}}

    # unavailable:
    #   friendly_name: 'Sensors that need attention'
    #   value_template: >
    #     {{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | length }}
    #   attribute_templates:
    #     entities: >
    #       {{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | map(attribute='entity_id') | list | join('\n') }}